steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install jupyter
        mkdir /workspace/scripts
        for f in examples/*.ipynb; do jupyter nbconvert --to script $f --output-dir /workspace/scripts; done
  - name: python
    args:
      - '-c'
      - >
        tar -C /workspace -czvf scripts.tar.gz scripts
    entrypoint: bash
    id: Tar extracted scripts
artifacts:
  objects:
    location: 'gs://sw_testing_artifacts/notebooks'
    paths:
      - /workspace/scripts.tar.gz
